{"uuid": "d4654588-1135-485b-9ff1-d381d6101ef8", "children": ["004be54a-4f30-456c-a31b-70624747108c"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "ValueError: response body:\n{\"message\":\"API rate limit exceeded for 109.252.157.243. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)\",\"documentation_url\":\"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting\"}\n\nrequest url:\nhttps://api.github.com/repos/mozilla/geckodriver/releases/latest\nresponse headers:\n{'Date': 'Mon, 04 Nov 2024 05:39:48 GMT', 'Server': 'Varnish', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'deny', 'X-XSS-Protection': '1; mode=block', 'Content-Security-Policy': \"default-src 'none'; style-src 'unsafe-inline'\", 'Access-Control-Allow-Origin': '*', 'Access-Control-Expose-Headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-RateLimit-Used, X-RateLimit-Resource, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset', 'Content-Type': 'application/json; charset=utf-8', 'Referrer-Policy': 'origin-when-cross-origin, strict-origin-when-cross-origin', 'X-GitHub-Media-Type': 'github.v3; format=json', 'X-RateLimit-Limit': '60', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1730699751', 'X-RateLimit-Resource': 'core', 'X-RateLimit-Used': '60', 'Content-Length': '281', 'X-GitHub-Request-Id': '08B2:2B966F:F91C8D7:FCC4CDF:67285E24'}\n\n", "trace": "  File \"/Users/user/PycharmProjects/Diplom/Diplom_3/.venv/lib/python3.9/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/Users/user/PycharmProjects/Diplom/Diplom_3/.venv/lib/python3.9/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/Users/user/PycharmProjects/Diplom/Diplom_3/.venv/lib/python3.9/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/user/PycharmProjects/Diplom/Diplom_3/.venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/user/PycharmProjects/Diplom/Diplom_3/.venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/user/PycharmProjects/Diplom/Diplom_3/conftest.py\", line 33, in browser\n    driver = webdriver.Firefox(service=FirefoxService(GeckoDriverManager().install()))\n  File \"/Users/user/PycharmProjects/Diplom/Diplom_3/.venv/lib/python3.9/site-packages/webdriver_manager/firefox.py\", line 39, in install\n    driver_path = self._get_driver_binary_path(self.driver)\n  File \"/Users/user/PycharmProjects/Diplom/Diplom_3/.venv/lib/python3.9/site-packages/webdriver_manager/core/manager.py\", line 35, in _get_driver_binary_path\n    binary_path = self._cache_manager.find_driver(driver)\n  File \"/Users/user/PycharmProjects/Diplom/Diplom_3/.venv/lib/python3.9/site-packages/webdriver_manager/core/driver_cache.py\", line 107, in find_driver\n    driver_version = self.get_cache_key_driver_version(driver)\n  File \"/Users/user/PycharmProjects/Diplom/Diplom_3/.venv/lib/python3.9/site-packages/webdriver_manager/core/driver_cache.py\", line 154, in get_cache_key_driver_version\n    return driver.get_driver_version_to_download()\n  File \"/Users/user/PycharmProjects/Diplom/Diplom_3/.venv/lib/python3.9/site-packages/webdriver_manager/core/driver.py\", line 48, in get_driver_version_to_download\n    return self.get_latest_release_version()\n  File \"/Users/user/PycharmProjects/Diplom/Diplom_3/.venv/lib/python3.9/site-packages/webdriver_manager/drivers/firefox.py\", line 29, in get_latest_release_version\n    resp = self._http_client.get(\n  File \"/Users/user/PycharmProjects/Diplom/Diplom_3/.venv/lib/python3.9/site-packages/webdriver_manager/core/http.py\", line 36, in get\n    self.validate_response(resp)\n  File \"/Users/user/PycharmProjects/Diplom/Diplom_3/.venv/lib/python3.9/site-packages/webdriver_manager/core/http.py\", line 19, in validate_response\n    raise ValueError(\n"}, "start": 1730698788000, "stop": 1730698788727}], "start": 1730698788000, "stop": 1730698788771}